pipeline_name: "voice_generator"

data_sourcing:
  data_source: "package_data"
  quantization_bits: 8
  sample_rate: 8000 

model_params:
  sequence_length: 256
  embedding_dim: 128
  hidden_size: 256

training_params:
  epochs: 10 # Daha az epoch ile daha hızlı sonuç alalım
  lr: 0.001
  # YENİ: Batch size ekledik, pipeline bunu kullanacak
  batch_size: 128